version: "3.6"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build:
      context: .
      dockerfile: python.dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - "8082:80"
    command: python ./manage.py runserver 0.0.0.0:80
    depends_on:
      - db